description: 'Setup VPN connections'
static_routing: False
services:
  enabled:
    - 'common'
nat:
  ami_id:
    # VyOS AMI's. Created using Packer from vyos-images
    us-east-1: ami-57717d40
    us-east-2: ami-f3a7fd96
    us-west-2: ami-af4ee4cf
  # The ssh key must be available in all relevant regions
  #key_name: 'ssh-key-name'
  key_name: 'amos-home'
  # m3.medium is the cheapest EC2 instance type with "moderate"
  # network petformance (http://www.ec2instances.info/), but it's
  # not available in all regions so I picked a cheaper instance just for
  # demonstration
  instance_type: t2.small
  sg_egress_rules:
    # allow access to anywhere outside
    - protocol: '-1' # Any
      cidr: 0.0.0.0/0
      port: -1 # Any
  extra_ingress_sources:
#    - CIDR
